/* This file is copyright by Immersive Systems, Inc.  All rights
 * reserved.  You are permitted to use this file subject to
 * the provisions and restrictions in the license agreement, which
 * is in the file LICENSE or LICENSE.txt or LICENSE.html.  If this
 * set of files does not contain a file by one of the three
 * preceding names, please contact the Metatopia project at
 * sourceforge.net or at immersive.com.
 */

/* Header file for setting the rendering engine
 * by Marc de Groot.
 * Copyright (c) Marc de Groot.  All rights reserved.
 */

#define	NO_RENDERING	0
#define	RENDERWARE	1
#define	REND386		2

/***** Set the renderer here *****/
#define	RENDERING	RENDERWARE

