/* This file is copyright by Immersive Systems, Inc.  All rights
 * reserved.  You are permitted to use this file subject to
 * the provisions and restrictions in the license agreement, which
 * is in the file LICENSE or LICENSE.txt or LICENSE.html.  If this
 * set of files does not contain a file by one of the three
 * preceding names, please contact the Metatopia project at
 * sourceforge.net or at immersive.com.
 */

#define FPLUS	0
#define FMINUS	1
#define FTIMES	2
#define FDIVIDE	3
#define FMOD	4
#define FNEGATE	5
#define FSIN	6
#define FCOS	7
#define FTAN	8
#define FLOG	9
#define FLN	10
#define FATAN	11
#define FATAN2	12
#define FASIN	13
#define FACOS	14
#define FCEIL	15
#define FCOSH	16
#define FSINH	17
#define TANH	18
#define FSQRT	19
#define FEXP	20
#define FABS	21
#define FFLOOR	22
#define FPOW	23
#define FDUP	24
#define FDROP	25
#define FOVER	26
#define FSWAP	27
#define FROT	28
#define FMINROT	29

#define FDEPTH	1
#define FPSTORE	2
#define FSTORE	3
#define FFETCH	4
#define FINT	5
#define FFLOAT	6
#define FPOP	7
#define FPUSH	8
#define FSTRING	9
#define ESTRING	10
#define FEQ	11
#define FNEQ	12
#define FLT	13
#define FGT	14
#define FLEQ	15
#define FGEQ	16
#define FZEQ	17
#define FZNEQ	18
#define FZLT	19
#define FZGT	20
#define FZLEQ	21
#define FZGEQ	22
#define FPICK	23
#define FNUMQUES 24
#define FNUMBER	25
